In [26]:
merged

  account_nm amount  note ofcps        sj_div         sj_nm
1        이재용   1.63  55.0    회장  SHAREHOLDERS  최대주주 주식소유 현황
4        경계현   0.00  61.0    사장  SHAREHOLDERS  최대주주 주식소유 현황
5        노태문   0.00  55.0    사장  SHAREHOLDERS  최대주주 주식소유 현황
6        박학규   0.00  59.0    사장  SHAREHOLDERS  최대주주 주식소유 현황
7        이정배   0.00  57.0    사장  SHAREHOLDERS  최대주주 주식소유 현황
8        김한조   0.00  50.0    상무  SHAREHOLDERS  최대주주 주식소유 현황
9        김한조   0.00  67.0    이사  SHAREHOLDERS  최대주주 주식소유 현황

In [35]:
merged['name'] = merged['account_nm'] + '(' + merged['ofcps'] + ',' + merged['note'].apply(lambda val: str(int(val))) + ')'

In [36]:
merged

  account_nm amount  note ofcps        sj_div         sj_nm        name
1        이재용   1.63  55.0    회장  SHAREHOLDERS  최대주주 주식소유 현황  이재용(회장,55)
4        경계현   0.00  61.0    사장  SHAREHOLDERS  최대주주 주식소유 현황  경계현(사장,61)
5        노태문   0.00  55.0    사장  SHAREHOLDERS  최대주주 주식소유 현황  노태문(사장,55)
6        박학규   0.00  59.0    사장  SHAREHOLDERS  최대주주 주식소유 현황  박학규(사장,59)
7        이정배   0.00  57.0    사장  SHAREHOLDERS  최대주주 주식소유 현황  이정배(사장,57)
8        김한조   0.00  50.0    상무  SHAREHOLDERS  최대주주 주식소유 현황  김한조(상무,50)
9        김한조   0.00  67.0    이사  SHAREHOLDERS  최대주주 주식소유 현황  김한조(이사,67)